In [1]:
import sys

print(sys.executable)

/Users/eaintmyintmon/Development/DataAnalysis Projects/MyComputerAnalytics/.venv/bin/python

In [2]:
import pandas as pd

products = pd.read_csv("../data/raw/products.csv")
branches = pd.read_csv("../data/raw/branches.csv")
suppliers = pd.read_csv("../data/raw/suppliers.csv")
purchases = pd.read_csv("../data/raw/purchases.csv")
sales = pd.read_csv("../data/raw/sales.csv")
inventory = pd.read_csv("../data/raw/inventory.csv")

In [3]:
print("Products:", products.shape)
print("Branches:", branches.shape)
print("Suppliers:", suppliers.shape)
print("Purchases:", purchases.shape)
print("Sales:", sales.shape)
print("Inventory:", inventory.shape)

Products: (31, 7)
Branches: (3, 4)
Suppliers: (7, 3)
Purchases: (1800, 8)
Sales: (3000, 11)
Inventory: (62, 8)

In [4]:
display(products.head())
display(branches.head())
display(suppliers.head())
display(purchases.head())
display(sales.head())
display(inventory.head())

,ItemCode,ItemDescription,Category,Supplier,BuyPrice,SellPrice_LL,DealerPrice_LL
0,MOUSE001,Wireless Mouse,Accessories,ABC Supplier,5000,8500,8000
1,MOUSE002,Wired Mouse,Accessories,ABC Supplier,3000,5500,5200
2,KB001,USB Keyboard,Accessories,XYZ Supplier,7000,12000,11000
3,KB002,Wireless Keyboard,Accessories,XYZ Supplier,12000,19000,17500
4,BAG001,"Laptop Bag 15.6""",Accessories,ABC Supplier,6500,13500,12500

  BranchCode  BranchName City    Status
0        LLM  LLM Branch  LLM    Active
1         NS   NS Branch   NS  Inactive
2        TGI  TGI Branch  TGI    Active

  SupplierCode      SupplierName          SupplierCategory
0       SUP001      ABC Supplier  Accessories & Components
1       SUP002      XYZ Supplier     Accessories & Storage
2       SUP003     Tech Supplier      Computer Accessories
3       SUP004    Local Supplier       General Accessories
4       SUP005  Network Supplier      Networking Equipment

,PurchaseID,PurchaseDate,BranchCode,SupplierCode,ItemCode,Quantity,UnitBuyPrice,TotalCost
0,PUR00001,2025-12-12,TGI,SUP007,MON002,2,478033.27,956066.54
1,PUR00002,2026-03-07,LLM,SUP001,RAM001,5,58751.64,293758.20
2,PUR00003,2025-10-20,TGI,SUP007,DESK001,5,1265142.73,6325713.65
3,PUR00004,2025-11-04,LLM,SUP002,KB002,39,12136.66,473329.74
4,PUR00005,2025-12-10,TGI,SUP006,SOFT002,29,81915.71,2375555.59

,SaleID,SaleDate,BranchCode,ItemCode,Quantity,UnitSalePrice,UnitCost,Revenue,COGS,GrossProfit,GrossMarginPct
0,S00001,2026-04-13,TGI,KB001,5,12000,7000,60000,35000,25000,41.666667
1,S00002,2026-01-21,LLM,KB001,3,12000,7000,36000,21000,15000,41.666667
2,S00003,2026-07-22,TGI,HUB001,3,12500,7000,37500,21000,16500,44.000000
3,S00004,2026-05-30,LLM,SSD001,2,75000,55000,150000,110000,40000,26.666667
4,S00005,2026-02-07,LLM,MON002,1,650000,500000,650000,500000,150000,23.076923

,BranchCode,ItemCode,OpeningStock,PurchasedQty,SoldQty,CurrentStock,UnitCost,InventoryValue
0,LLM,MOUSE001,48,540,243,345,5000,1725000
1,LLM,MOUSE002,38,547,236,349,3000,1047000
2,LLM,KB001,24,479,208,295,7000,2065000
3,LLM,KB002,17,607,264,360,12000,4320000
4,LLM,BAG001,30,438,246,222,6500,1443000

### Checking missing values

In [5]:
print("Missing values in products:")
print(products.isnull().sum())

print("\nMissing values in branches:")
print(branches.isnull().sum())

print("\nMissing values in suppliers:")
print(suppliers.isnull().sum())

print("\nMissing values in purchases:")
print(purchases.isnull().sum())

print("\nMissing values in sales:")
print(sales.isnull().sum())

print("\nMissing values in inventory:")
print(inventory.isnull().sum())

Missing values in products:
ItemCode           0
ItemDescription    0
Category           0
Supplier           0
BuyPrice           0
SellPrice_LL       0
DealerPrice_LL     0
dtype: int64

Missing values in branches:
BranchCode    0
BranchName    0
City          0
Status        0
dtype: int64

Missing values in suppliers:
SupplierCode        0
SupplierName        0
SupplierCategory    0
dtype: int64

Missing values in purchases:
PurchaseID      0
PurchaseDate    0
BranchCode      0
SupplierCode    0
ItemCode        0
Quantity        0
UnitBuyPrice    0
TotalCost       0
dtype: int64

Missing values in sales:
SaleID            0
SaleDate          0
BranchCode        0
ItemCode          0
Quantity          0
UnitSalePrice     0
UnitCost          0
Revenue           0
COGS              0
GrossProfit       0
GrossMarginPct    0
dtype: int64

Missing values in inventory:
BranchCode        0
ItemCode          0
OpeningStock      0
PurchasedQty      0
SoldQty           0
CurrentStock      0
UnitCost          0
InventoryValue    0
dtype: int64

### Check duplicate

In [6]:
print("Duplicate Product IDs:", products["ItemCode"].duplicated().sum())
print("Duplicate Purchase IDs:", purchases["PurchaseID"].duplicated().sum())
print("Duplicate Sale IDs:", sales["SaleID"].duplicated().sum())

Duplicate Product IDs: 0
Duplicate Purchase IDs: 0
Duplicate Sale IDs: 0

### Check negative inventory

In [7]:
print(
    "Negative inventory records:",
    (inventory["CurrentStock"] < 0).sum()
)

Negative inventory records: 0

### Check inventory stock

In [8]:
inventory["CalculatedStock"] = (
    inventory["OpeningStock"]
    + inventory["PurchasedQty"]
    - inventory["SoldQty"]
)

inventory["StockCheck"] = (
    inventory["CalculatedStock"]
    == inventory["CurrentStock"]
)

print("Incorrect inventory calculations:")
print((inventory["StockCheck"] == False).sum())

Incorrect inventory calculations:
0

### Check Sales calculation

In [9]:
sales["CalculatedRevenue"] = (
    sales["Quantity"] * sales["UnitSalePrice"]
)

sales["CalculatedCOGS"] = (
    sales["Quantity"] * sales["UnitCost"]
)

sales["CalculatedGrossProfit"] = (
    sales["CalculatedRevenue"] - sales["CalculatedCOGS"]
)

print(
    "Revenue errors:",
    (sales["Revenue"] != sales["CalculatedRevenue"]).sum()
)

print(
    "COGS errors:",
    (sales["COGS"] != sales["CalculatedCOGS"]).sum()
)

print(
    "Gross profit errors:",
    (sales["GrossProfit"] != sales["CalculatedGrossProfit"]).sum()
)

Revenue errors: 0
COGS errors: 0
Gross profit errors: 0

### Validation done. Clean temporary columns

In [10]:
inventory.drop(
    columns=["CalculatedStock", "StockCheck"],
    inplace=True
)

sales.drop(
    columns=[
        "CalculatedRevenue",
        "CalculatedCOGS",
        "CalculatedGrossProfit"
    ],
    inplace=True
)

In [11]:
print(inventory.shape)
print(sales.shape)

(62, 8)
(3000, 11)

The following code is for updating products.csv to match with database schema.

In [14]:
supplier_mapping = {
    "ABC Supplier": "SUP001",
    "XYZ Supplier": "SUP002",
    "Tech Supplier": "SUP003",
    "Local Supplier": "SUP004",
    "Network Supplier": "SUP005",
    "Software Supplier": "SUP006",
    "Computer Supplier": "SUP007"
}

products_db = products.copy()

products_db["supplier_code"] = products_db["Supplier"].map(supplier_mapping)

products_db = products_db.rename(columns={
    "ItemCode": "item_code",
    "ItemDescription": "item_description",
    "Category": "category",
    "BuyPrice": "buy_price",
    "SellPrice_LL": "sell_price_ll",
    "DealerPrice_LL": "dealer_price_ll"
})

products_db = products_db[
    [
        "item_code",
        "item_description",
        "category",
        "supplier_code",
        "buy_price",
        "sell_price_ll",
        "dealer_price_ll"
    ]
]

display(products_db.head())

,item_code,item_description,category,supplier_code,buy_price,sell_price_ll,dealer_price_ll
0,MOUSE001,Wireless Mouse,Accessories,SUP001,5000,8500,8000
1,MOUSE002,Wired Mouse,Accessories,SUP001,3000,5500,5200
2,KB001,USB Keyboard,Accessories,SUP002,7000,12000,11000
3,KB002,Wireless Keyboard,Accessories,SUP002,12000,19000,17500
4,BAG001,"Laptop Bag 15.6""",Accessories,SUP001,6500,13500,12500

In [15]:
print("Shape:", products_db.shape)
print("Missing supplier codes:", products_db["supplier_code"].isnull().sum())
print("Supplier codes:", products_db["supplier_code"].unique())

Shape: (31, 7)
Missing supplier codes: 0
Supplier codes: <StringArray>
['SUP001', 'SUP002', 'SUP003', 'SUP004', 'SUP005', 'SUP006', 'SUP007']
Length: 7, dtype: str

In [16]:
products_db.to_csv(
    "../data/processed/products_db.csv",
    index=False
)

print("Saved successfully.")

Saved successfully.

In [17]:
products_db.to_csv(
    "../data/processed/products_db.csv",
    index=False
)

print("Saved successfully.")

Saved successfully.

In [18]:
print(purchases.columns.tolist())
print(purchases["SupplierCode"].unique())

['PurchaseID', 'PurchaseDate', 'BranchCode', 'SupplierCode', 'ItemCode', 'Quantity', 'UnitBuyPrice', 'TotalCost']
<StringArray>
['SUP007', 'SUP001', 'SUP002', 'SUP006', 'SUP003', 'SUP004', 'SUP005']
Length: 7, dtype: str

In [19]:
purchases_db = purchases.copy()

purchases_db = purchases_db.rename(columns={
    "PurchaseID": "purchase_id",
    "PurchaseDate": "purchase_date",
    "BranchCode": "branch_code",
    "SupplierCode": "supplier_code",
    "ItemCode": "item_code",
    "Quantity": "quantity",
    "UnitBuyPrice": "unit_buy_price",
    "TotalCost": "total_cost"
})

display(purchases_db.head())

,purchase_id,purchase_date,branch_code,supplier_code,item_code,quantity,unit_buy_price,total_cost
0,PUR00001,2025-12-12,TGI,SUP007,MON002,2,478033.27,956066.54
1,PUR00002,2026-03-07,LLM,SUP001,RAM001,5,58751.64,293758.20
2,PUR00003,2025-10-20,TGI,SUP007,DESK001,5,1265142.73,6325713.65
3,PUR00004,2025-11-04,LLM,SUP002,KB002,39,12136.66,473329.74
4,PUR00005,2025-12-10,TGI,SUP006,SOFT002,29,81915.71,2375555.59

In [20]:
print("Shape:", purchases_db.shape)
print("Missing values:", purchases_db.isnull().sum().sum())
print("Columns:", purchases_db.columns.tolist())

Shape: (1800, 8)
Missing values: 0
Columns: ['purchase_id', 'purchase_date', 'branch_code', 'supplier_code', 'item_code', 'quantity', 'unit_buy_price', 'total_cost']

In [21]:
purchases_db.to_csv(
    "../data/processed/purchases_db.csv",
    index=False
)

print("Saved successfully.")

Saved successfully.

In [22]:
print(sales.columns.tolist())

['SaleID', 'SaleDate', 'BranchCode', 'ItemCode', 'Quantity', 'UnitSalePrice', 'UnitCost', 'Revenue', 'COGS', 'GrossProfit', 'GrossMarginPct']

In [23]:
sales_db = sales.copy()

sales_db = sales_db.rename(columns={
    "SaleID": "sale_id",
    "SaleDate": "sale_date",
    "BranchCode": "branch_code",
    "ItemCode": "item_code",
    "Quantity": "quantity",
    "UnitSalePrice": "unit_sale_price",
    "UnitCost": "unit_cost",
    "Revenue": "revenue",
    "COGS": "cogs",
    "GrossProfit": "gross_profit",
    "GrossMarginPct": "gross_margin_pct"
})

display(sales_db.head())

,sale_id,sale_date,branch_code,item_code,quantity,unit_sale_price,unit_cost,revenue,cogs,gross_profit,gross_margin_pct
0,S00001,2026-04-13,TGI,KB001,5,12000,7000,60000,35000,25000,41.666667
1,S00002,2026-01-21,LLM,KB001,3,12000,7000,36000,21000,15000,41.666667
2,S00003,2026-07-22,TGI,HUB001,3,12500,7000,37500,21000,16500,44.000000
3,S00004,2026-05-30,LLM,SSD001,2,75000,55000,150000,110000,40000,26.666667
4,S00005,2026-02-07,LLM,MON002,1,650000,500000,650000,500000,150000,23.076923

In [24]:
print("Shape:", sales_db.shape)
print("Missing values:", sales_db.isnull().sum().sum())
print("Columns:", sales_db.columns.tolist())

Shape: (3000, 11)
Missing values: 0
Columns: ['sale_id', 'sale_date', 'branch_code', 'item_code', 'quantity', 'unit_sale_price', 'unit_cost', 'revenue', 'cogs', 'gross_profit', 'gross_margin_pct']

In [25]:
sales_db.to_csv(
    "../data/processed/sales_db.csv",
    index=False
)

print("Saved successfully.")

Saved successfully.

In [26]:
inventory_db = inventory.copy()

inventory_db = inventory_db.rename(columns={
    "BranchCode": "branch_code",
    "ItemCode": "item_code",
    "OpeningStock": "opening_stock",
    "PurchasedQty": "purchased_qty",
    "SoldQty": "sold_qty",
    "CurrentStock": "current_stock",
    "UnitCost": "unit_cost",
    "InventoryValue": "inventory_value"
})

display(inventory_db.head())

,branch_code,item_code,opening_stock,purchased_qty,sold_qty,current_stock,unit_cost,inventory_value
0,LLM,MOUSE001,48,540,243,345,5000,1725000
1,LLM,MOUSE002,38,547,236,349,3000,1047000
2,LLM,KB001,24,479,208,295,7000,2065000
3,LLM,KB002,17,607,264,360,12000,4320000
4,LLM,BAG001,30,438,246,222,6500,1443000

In [27]:
print("Shape:", inventory_db.shape)
print("Missing values:", inventory_db.isnull().sum().sum())
print("Columns:", inventory_db.columns.tolist())

Shape: (62, 8)
Missing values: 0
Columns: ['branch_code', 'item_code', 'opening_stock', 'purchased_qty', 'sold_qty', 'current_stock', 'unit_cost', 'inventory_value']

In [28]:
inventory_db.to_csv(
    "../data/processed/inventory_db.csv",
    index=False
)

print("Saved successfully.")

Saved successfully.